project/apps/authentification/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'authentification'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='authentification/login.html', next_page='authentification:login'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='authentification/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeView.as_view(
         template_name='authentification/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
         template_name='authentification/password_reset_form.html', email_template_name='authentification/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
         template_name='authentification/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
         template_name='authentification/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
         template_name='authentification/password_reset_complete.html'), name='password_reset_complete'),
]

project/apps/dash/urls.py
from django.urls import path, include
from . import views

app_name = 'dash'
urlpatterns = [
    path('dashboard_emp', views.dash_emp, name='employe_dashbored'),
    path('dashboard_man', views.dash_man, name='manager_dashbored'),
    path('dashboard_responsible', views.dash_responsible, name='responsible_dashbored'),
    path('profile', views.profile , name='profile'),
    path('profile/<str:pk>', views.view_profile , name='view_profile'),
    path('edit_profile/<str:pk>', views.edit_profile , name='edit_profile'),
    path('ma_fiche_pointage/<str:pk>', views.ma_fiche_pointage , name='ma_fiche_pointage'),
    path('fiche_pointage/', views.fiche_pointage , name='fiche_pointage'),
    path('mes_collaborateurs', views.mes_collaborateurs , name='mes_collaborateurs'),
    path('my_teams', views.my_teams , name='my_teams'),
    path('schedules', views.schedules , name='schedules'),
    path('schedule/<str:pk>', views.schedule , name='schedule'),
    path('my_schedule/<str:pk>', views.my_schedule , name='my_schedule'),
    path('modify_schedule/<str:pk>', views.modify_schedule , name='modify_schedule'),
    path('assign_schedule/<str:pk>', views.assign_schedule , name='assign_schedule'),
    path('create_schedule', views.create_schedule , name='create_schedule'),
    path('delete_schedule/<str:pk>', views.delete_schedule , name='delete_schedule'),
    path('delete_employe_schedule/<str:pk>', views.delete_employe_schedule , name='delete_employe_schedule'),
    path('create_team', views.create_team , name='create_team'),
    path('assign_team/<str:pk>', views.assign_team , name='assign_team'),
    path('modify_team/<str:pk>', views.modify_team , name='modify_team'),
    path('delete_team/<str:pk>', views.delete_team , name='delete_team'),
    path('delete_employe_team/<str:pk>', views.delete_employe_team , name='delete_employe_team'),
    path('mes_employes', views.mes_employes , name='mes_employes'),
    path('fiche_pointage_all/', views.fiche_pointage_all , name='fiche_pointage_all'),
    path('mes_equipes/', views.mes_equipes , name='mes_equipes'),
    path('equipe_view/<str:pk>', views.equipe_view , name='equipe_view'), 
    path('affectations_view/', views.affectations_view , name='affectations_view'), 


    #path('mon-equipe/', views.mon_equipe , name='mon_equipe'),
    path('export_shift/', views.export_shift , name='export_shift'),
    path('import_shift/', views.import_shift , name='import_shift'),

    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pointage/', include('apps.pointage.urls', namespace='pointage')),
    path('dash/', include('apps.dash.urls', namespace='dash')),
    path('', include('apps.authentification.urls', namespace='authentification')),
    path('', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="fr">
<head>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"/>
   <title>{% block title %}{% endblock %}</title>
</head>
<body>

    {% if user.is_authenticated %}
        <a href="{% url 'authentification:password_change' %}" > change  password    </a>
        <a href="{% url 'authentification:logout' %}" > logout   </a> 
    {% else %}
        
       
    {% endif %}
   <div class="container">
       {% block content %}
       {% endblock %}
   </div>
       

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

project/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/datepicker-bs4.min.css' %}" />
  
 
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/Chart.js' %}"></script>
  <script src="{% static 'js/Chart.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/datepicker-full.min.js' %}"></script>
  <script src="{% static 'js/loader.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  <!--Scripts-->
  {% block scripts %} {% endblock scripts %}

</head>



<body>



    <div class="wrapper d-flex">
        <!-- Menu -->
        {% include "side_menu.html" %}
        <!-- Mainframe -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- NavBar -->
                    {% include "navbar.html" %}


                    <!--Contenu-->
                    {% block content %} {% endblock content %}

                    

                </div>
            </div>
        </div>
    </div>

    
 





</body>

</html>

project/templates/navbar.html
<div class=" col-12 p-0">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ml-auto navbar-custom">
      <button class="navbar-toggler sideMenuToggler" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <img id="nomapp" class="nomapp navbar-brand" src="/media/images/attime.png" alt="ATTime">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <img src="{{ request.user.employe.picture.url }}" class="profile-pic rounded-circle" alt="">
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              {{ request.user.username|capfirst }} <i class="fas fa-angle-down"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'dash:view_profile' pk=request.user.id %}"> <i class="fas fa-user"></i> Mon Profil</a>
              <a class="dropdown-item" href="#"> <i class="fas fa-cog"></i> Parametre</a>
              <a class="dropdown-item" href="#"> <i class="fas fa-question-circle"></i> Support</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'authentification:logout' %}"> <i class="fas fa-sign-out-alt"></i> Se Déconnecter</a>
            </div>
          </li>
  
        </ul>
  
      </div>
    </nav>
</div>

project/templates/side_menu.html
{% if request.user.role == 3 %}
    <div class="sideMenu bg-secondaryy">
        
        <div class="sideBar">
            <img id="logoL" class="logoL" src="/media/images/logo.png" alt="ATTime">
            <img id="logoS" class="logoS" src="/media/images/logoS.png" alt="ATTime">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'dash:responsible_dashbored' %}" class="nav-link">
                    <i class="icon fas fa-home"></i>
                    <span class="text">Mon tableau de bord</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:view_profile' pk=request.user.id %}" class="nav-link">
                    <i class="icon fas fa-user"></i>
                    <span class="text">Mon profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:ma_fiche_pointage' pk=request.user.id %}" class="nav-link">
                    <i class="icon fas fa-hourglass-half"></i>
                    <span class="text">Ma fiche de pointage</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:mes_employes' %}" class="nav-link">
                    <i class="icon fas fa-address-book"></i>
                    <span class="text">Les employés</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'dash:my_teams' %}" class="nav-link">
                    <i class="icon fas fa-users"></i>
                    <span class="text">Les Equipes</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'dash:schedules' %}" class="nav-link">
                    <i class="icon fas fa-calendar-week"></i>
                    <span class="text">Les Plannings</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'dash:fiche_pointage_all' %}" class="nav-link">
                    <i class="icon fas fa-clock"></i>
                    <span class="text">Pointage</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'dash:affectations_view' %}" class="nav-link">
                    <i class="icon fas fa-book"></i>
                    <span class="text">Affectations</span>
                </a>
            </li>
            
            <li class="nav-item liToggle fixed-bottom">
                <a href="#" class="nav-link sideMenuToggler" id='sideMenuToggler'>
                <i class="icon fas fa-chevron-circle-left"></i>
                </a>
            </li>
        </ul>
        </div>
    </div>
{% elif request.user.role == 2 %}
    <div class="sideMenu bg-secondaryy">
        <div class="sideBar">
            <img id="logoL" class="logoL" src="/media/images/logo.png" alt="ATTime">
            <img id="logoS" class="logoS" src="/media/images/logoS.png" alt="ATTime">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'dash:manager_dashbored' %}" class="nav-link">
                    <i class="icon fas fa-home"></i>
                    <span class="text">Mon tableau de bord</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:view_profile' pk=request.user.id %}" class="nav-link">
                    <i class="icon fas fa-user"></i>
                    <span class="text">Mon profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:ma_fiche_pointage' pk=request.user.id  %}" class="nav-link">
                    <i class="icon far fa-calendar-alt"></i>
                    <span class="text">Ma fiche de pointage</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'dash:mes_equipes'  %}" class="nav-link">
                    <i class="icon fas fa-users"></i>
                    <span class="text">Mes équipes</span>
                </a>

            </li><li class="nav-item">
                <a href="{% url 'dash:fiche_pointage' %}" class="nav-link">
                    <i class="icon fas fa-clock"></i>
                    <span class="text">pointage</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url  'dash:mes_collaborateurs'%}" class="nav-link">
                    <i class="icon fas fa-address-book"></i>
                    <span class="text">Mes collaboratteurs</span>
                </a>
            </li>

            {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="icon fas fa-users"></i>
                    <span class="text">Mon équipe</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a href="{% url 'dash:fiche_pointage' %}" class="nav-link">
                        <i class="icon fas fa-hourglass-half"></i>
                        <span class="text">Fiche de pointage</span>
                    </a>

                    <a href="{% url 'dash:mes_collaborateurs' %}" class="nav-link">
                        <i class="icon far fa-calendar-alt"></i>
                        <span class="text">Mes collaboratteurs</span>
                    </a>
            </li> {% endcomment %}
            <li class="nav-item liToggle fixed-bottom">
                <a href="#" class="nav-link sideMenuToggler" id='sideMenuToggler'>
                <i class="icon fas fa-chevron-circle-left"></i>
                </a>
            </li>
        </ul>
        </div>
    </div>
{% elif request.user.role == 1 %}

    <div class="sideMenu bg-secondaryy">
        <div class="sideBar">
            <img id="logoL" class="logoL" src="/media/images/logo.png" alt="ATTime">
            <img id="logoS" class="logoS" src="/media/images/logoS.png" alt="ATTime">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'dash:employe_dashbored' %}" class="nav-link">
                    <i class="icon fas fa-home"></i>
                    <span class="text">Mon tableau de bord</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:view_profile' pk=request.user.id %}" class="nav-link">
                    <i class="icon fas fa-user"></i>
                    <span class="text">Mon profil</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'dash:ma_fiche_pointage' pk=request.user.id %}" class="nav-link">
                    <i class="icon fas fa-hourglass-half"></i>
                    <span class="text">Ma fiche de pointage</span>
                </a>
            </li>

             <li class="nav-item">
                {% if request.user.employe.planing.id  %}
                    <a href="{% url 'dash:my_schedule' pk=request.user.employe.planing.id %}" class="nav-link">
                    <i class="icon far fa-calendar-alt"></i>
                    <span class="text">Mon planning</span>
                </a>
                {% else %}
                {% endif %}
                
            </li>
            <li class="nav-item liToggle fixed-bottom">
                <a href="#" class="nav-link sideMenuToggler" id='sideMenuToggler'>
                <i class="icon fas fa-chevron-circle-left"></i>
                </a>
            </li>
            
        </ul>
        </div>
    </div>
{% else %}

{% endif %}