project/apps/authentification/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'authentification'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='authentification/login.html', next_page='authentification:login'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='authentification/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeView.as_view(
         template_name='authentification/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
         template_name='authentification/password_reset_form.html', email_template_name='authentification/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
         template_name='authentification/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
         template_name='authentification/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
         template_name='authentification/password_reset_complete.html'), name='password_reset_complete'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pointage/', include('apps.pointage.urls', namespace='pointage')),
    path('dash/', include('apps.dash.urls', namespace='dash')),
    path('', include('apps.authentification.urls', namespace='authentification')),
    path('', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/authentification/forms.py
from django import forms
from django.contrib.auth import authenticate

class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control",'placeholder':"Nom d'utilisateur"}),label='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control",'placeholder':"Mot de passe"}),label='')

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Votre nom d'utilisateur est incorrecte")
            if not user.check_password(password):
                raise forms.ValidationError("Votre mot de passe est incorrecte")
            if not user.is_active:
                raise forms.ValidationError("Votre compte n'est pas active")
        return super(UserLoginForm, self).clean(*args, **kwargs)

project/apps/authentification/views.py
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from apps.dash.views import dash_emp, dash_man, dash_responsible
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User

from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from .forms import UserLoginForm

# Create your views here.


class Login(LoginView):
    template_name = 'authentification/login.html'

    def get_success_url(self):  # if username and password are correct
        role = self.request.user.role

        if role == 1:
            print("Je suis un employé")
            return reverse('dash:employe_dashbored')
        elif role == 2:
            print("Je suis un manager")
            return reverse('dash:manager_dashbored')
        elif role == 3:
            print("Je suis un chef de projet")
            return reverse('dash:responsible_dashbored')
        else:
            print("Je suis abehri")


@login_required(redirect_field_name='login')  # Require auth
def dash(request):  # Check role of user
    role = request.user.role
    if role == 1:
        print("Employe")
        html = "<html><body>Employe</body></html>"
        return HttpResponse(html)
    elif role == 2:
        print("Manager")
        html = "<html><body>Manager</body></html>"
        return HttpResponse(html)
    elif role == 3:
        print("Chef de projet")
        html = "<html><body>Chef de projet</body></html>"
        return HttpResponse(html)
    else:
        raise Http404("Not Found")



def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        role = user.role
        print('tttttt')

        if role == 1:
            print("Je suis un employé")
           
            return redirect(reverse('dash:employe_dashbored')) 
        elif role == 2:
            print("Je suis un manager")
            return redirect(reverse('dash:manager_dashbored'))
        elif role == 3:
            print("Je suis un chef de projet")
            return redirect(reverse('dash:responsible_dashbored'))
        else:
            print("Je suis abehri")
        return redirect('/')   
    context = {
        'form' : form,
    }
    return render(request, "authentification/login.html", context)

project/templates/authentification/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block nav %} {% endblock %}
{% block title %}Ma page d'accueil{% endblock %}
{% block content %}

    <div class="form">
        <form class="form-signin mt-5" method="POST" action="{% url 'authentification:login' %}">
            <img class="mb-4" src="/media/images/attime.png" alt="" width="140">
            <h1 class="h4 mb-3 font-weight-normal">Veuillez vous authentifier</h1>
            {% csrf_token %}
            {{ form }}
            <a class="mdpl" href="{% url 'authentification:password_reset' %}"> Mot de passe oublié ? </a>
            <button type="submit" class="btn btn-lg mt-2 btn-primary btn-block"> Se connecter</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>  
        </form>
    </div>
{% endblock %}

project/templates/authentification/password_change_done.html
{% extends 'base.html' %}


{% block content %}
<h2>  password change donne </h2>

{% endblock content %}

project/templates/authentification/password_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

 {% block content %}
    <h2> password chnage  page </h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit"> password chnage </button>
    </form>
{% endblock content %}

project/templates/authentification/password_reset_complete.html
{% extends 'base.html' %} 
{% block content %}


<h2>  password changed with succssed </h2>

<p> you  may now <a href="{% url 'authentification:login' %}"> log in </a> again  </p>

{% endblock content %}

project/templates/authentification/password_reset_confirm.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block content %}

<h2> set new password page </h2>
{% if validlink %}
    <form action="" method="post">
        {% csrf_token %}   
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" > reset password </button>
    </form>
{% else %}
    <p>invalide token </p>
    <a href="{% url 'authentification:password_reset' %}" >Request a new password token  </a>
{% endif %}

{% endblock content %}

project/templates/authentification/password_reset_done.html
{% extends 'base.html' %} 

{% block content %}
<h2> password reset done  page  </h2>
<p> password changed withe sucesse  
We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

{% endblock content %}

project/templates/authentification/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'authentification:password_reset_confirm' uidb64=uid token=token %}

project/templates/authentification/password_reset_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<h2>  reset password page </h2>
<form action="" method="post">
    {% csrf_token %}  
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" > reset your password </button>
</form>

{% endblock content %}