project/apps/dash/urls.py
from django.urls import path, include
from . import views

app_name = 'dash'
urlpatterns = [
    path('dashboard_emp', views.dash_emp, name='employe_dashbored'),
    path('dashboard_man', views.dash_man, name='manager_dashbored'),
    path('dashboard_responsible', views.dash_responsible, name='responsible_dashbored'),
    path('profile', views.profile , name='profile'),
    path('profile/<str:pk>', views.view_profile , name='view_profile'),
    path('edit_profile/<str:pk>', views.edit_profile , name='edit_profile'),
    path('ma_fiche_pointage/<str:pk>', views.ma_fiche_pointage , name='ma_fiche_pointage'),
    path('fiche_pointage/', views.fiche_pointage , name='fiche_pointage'),
    path('mes_collaborateurs', views.mes_collaborateurs , name='mes_collaborateurs'),
    path('my_teams', views.my_teams , name='my_teams'),
    path('schedules', views.schedules , name='schedules'),
    path('schedule/<str:pk>', views.schedule , name='schedule'),
    path('my_schedule/<str:pk>', views.my_schedule , name='my_schedule'),
    path('modify_schedule/<str:pk>', views.modify_schedule , name='modify_schedule'),
    path('assign_schedule/<str:pk>', views.assign_schedule , name='assign_schedule'),
    path('create_schedule', views.create_schedule , name='create_schedule'),
    path('delete_schedule/<str:pk>', views.delete_schedule , name='delete_schedule'),
    path('delete_employe_schedule/<str:pk>', views.delete_employe_schedule , name='delete_employe_schedule'),
    path('create_team', views.create_team , name='create_team'),
    path('assign_team/<str:pk>', views.assign_team , name='assign_team'),
    path('modify_team/<str:pk>', views.modify_team , name='modify_team'),
    path('delete_team/<str:pk>', views.delete_team , name='delete_team'),
    path('delete_employe_team/<str:pk>', views.delete_employe_team , name='delete_employe_team'),
    path('mes_employes', views.mes_employes , name='mes_employes'),
    path('fiche_pointage_all/', views.fiche_pointage_all , name='fiche_pointage_all'),
    path('mes_equipes/', views.mes_equipes , name='mes_equipes'),
    path('equipe_view/<str:pk>', views.equipe_view , name='equipe_view'), 
    path('affectations_view/', views.affectations_view , name='affectations_view'), 


    #path('mon-equipe/', views.mon_equipe , name='mon_equipe'),
    path('export_shift/', views.export_shift , name='export_shift'),
    path('import_shift/', views.import_shift , name='import_shift'),

    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pointage/', include('apps.pointage.urls', namespace='pointage')),
    path('dash/', include('apps.dash.urls', namespace='dash')),
    path('', include('apps.authentification.urls', namespace='authentification')),
    path('', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/dash/models.py
from django.db import models


# Create your models here.

project/apps/pointage/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models import Count, Q
from random import choice
from django.utils import timezone

# Create your models here.


class EmployeManManager(models.Manager):
    def get_my_employe_stats(self, team, user_emp):
        return super().get_queryset().filter(Q(team__nom__contains=team), ~Q(user=user_emp)).values('team').annotate(nb_emp_in=Count(
            'user',
            filter=Q(iwssad=True)),
            nb_emp_out=Count(
            'user',
            filter=Q(iwssad=False)),
            nb_emp=Count(
            'user'
        ))

    def get_my_employe(self, team, user_emp):
        return super().get_queryset().filter(Q(team__titre__contains=team), ~Q(user=user_emp))


class User(AbstractUser):
    EMPLOYE = 1
    MANAGER = 2
    BOSS = 3

    ROLE_CHOICES = (
        (EMPLOYE, 'Employé'),
        (MANAGER, 'Manager'),
        (BOSS, 'Responsable'),
    )
    email = models.EmailField(unique=True)
    role = models.PositiveSmallIntegerField(
        choices=ROLE_CHOICES, blank=True, null=True)


class Employe(models.Model):
    MAN = 'H'
    WOMAN = 'F'
    GENDER = (
        (MAN, 'Homme'),
        (WOMAN, 'Femme'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    iwssad = models.BooleanField(default=False)
    finger_id = models.PositiveSmallIntegerField(unique=True, blank=True)
    is_uploaded = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    birthdate = models.DateField(
        auto_now=False, blank=True, null=True, verbose_name="Date naissance")
    birthplace = models.CharField(max_length=120, blank=True)
    address = models.CharField(
        max_length=200, blank=True, verbose_name="Adresse")
    phone1 = models.CharField(max_length=200, blank=True, null=True,
                              verbose_name="Téléphone professionnel")
    phone2 = models.CharField(max_length=200, blank=True, null=True,
                              verbose_name="Téléphone personnel")
    description = models.CharField(
        max_length=300, blank=True, null=True, verbose_name="Description")
    picture = models.ImageField(
        upload_to='images/', default='images/nounours.png', verbose_name="Photo de profil")
    team = models.ForeignKey(
        'Team', on_delete=models.SET_NULL, null=True, blank=True, related_name='employes')
    planing = models.ForeignKey(
        'Planing', on_delete=models.SET_NULL, blank=True, null=True, related_name='pemployes')
    gender = models.CharField(
        max_length=1,
        choices=GENDER,
        blank=True, null=True,
        verbose_name="Genre"
    )
    fonction =models.CharField(max_length=200, blank=True, null=True,
                              verbose_name="Fonction",default=".")
    observation = models.CharField(max_length=300, blank=True, null=True,
                              verbose_name="Remarque") 
    objects = models.Manager()
    manager = EmployeManManager()

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.genrate_finger_id()

        super(Employe, self).save(*args, **kwargs)

    def genrate_finger_id(self):
        # get ids alredy used
        used_id = self.get_used_id()
        # a liste of the interval
        my_list = list(range(2, 128))
        # a liste with thee possible valeus =interval-alredy used elements
        possible_values_list = set(my_list)-set(used_id)
        # print(possible_values_list)
        # a random ellment from this liste
        # print(choice(list(possible_values_list)))
        # set  the value to the finger id attribut
        self.finger_id = choice(list(possible_values_list))

    def get_used_id(self):
        my_id_list = [1, ]
        # get employes
        employes = Employe.objects.all()
        # get used finger id
        for employe in employes:
            my_id_list.append(employe.finger_id)
       # print(my_id_list)
        return my_id_list

    def delete_employe(self):
        self.is_delete = True
        self.save()

    def set_iwssad(self, is_iwssad):
        self.iwssad = is_iwssad
        self.save()

    # get the working hours of the corresponding day
    def get_today_hours(self):
        # get the day of the week
        today = timezone.now().date()
        dow = timezone.now().weekday()
        try:
            day = Day.objects.get(planing=self.planing, jds=dow)
            return day
        except:
            day = Day(jds=0, he1=timezone.now().time())
            return day
    # get the last shift of the employe

    def get_last_shift(self):
        try:
            shift = Shift.objects.filter(
                employe=self, day=timezone.now().date()).order_by('-number').first()
            print(f'last shift {shift}')
            return shift
        except:
            print('else of get_last_entry')
            return None


class Team(models.Model):
    titre = models.CharField(
        max_length=150, default='team', blank=True, null=True, verbose_name="Nom de l'équipe", unique=True)
    description = models.CharField(
        max_length=400, blank=True, null=True, verbose_name="Déscription de l'équipe")
    manager = models.ForeignKey(
        'Employe', verbose_name="manager de l'équipe", on_delete=models.SET_NULL, null=True, blank=True, related_name='managed_team')

    def __str__(self):
        return str(self.titre)


class Shift(models.Model):
    employe = models.ForeignKey('Employe', on_delete=models.CASCADE)
    number = models.PositiveSmallIntegerField(blank=True, null=True)
    day = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    he = models.TimeField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    hs = models.TimeField(
        auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return str(f"numero  : {self.number}/employé  : {self.employe}/joure  : {self.day}")

    def set_he(self):
        self.he = timezone.now()
        self.save()

    def set_hs(self):
        self.hs = timezone.now()
        self.save()


class Day(models.Model):

    DAY_OF_WEEK = ((5, 'Samedi'), (6, 'Dimanche'), (0, 'Lundi'),
                   (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'))
    #titre = models.CharField(max_length=150)

    jds = models.PositiveIntegerField(
        choices=DAY_OF_WEEK, blank=True, null=True)
    he1 = models.TimeField(auto_now=False, auto_now_add=False,
                           blank=True, null=True)
    hs1 = models.TimeField(auto_now=False, auto_now_add=False,
                           blank=True, null=True)
    he2 = models.TimeField(auto_now=False, auto_now_add=False,
                           blank=True, null=True)
    hs2 = models.TimeField(auto_now=False, auto_now_add=False,
                           blank=True, null=True)
    planing = models.ForeignKey(
        'Planing', on_delete=models.SET_NULL, blank=True, null=True, related_name='planing_days')

    def __str__(self):
        return str(self.jds)


class Planing (models.Model):
    titre = models.CharField(
        max_length=150, unique=True, blank=False, null=False)
    description = models.CharField(max_length=400, blank=True, null=True)

    def __str__(self):
        return str(self.titre)


class Affectation(models.Model):
    employe = models.ForeignKey(
        'Employe', on_delete=models.CASCADE, blank=True, null=True, related_name='affected_set')
    team = models.ForeignKey(
        'Team', on_delete=models.SET_NULL, blank=True, null=True,)
    enter_day= models.DateTimeField(
        auto_now=False, auto_now_add=False, blank=True, null=True)    
    exit_day= models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    team_name =models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return str(f"ID {self.id} {self.employe} a etais affecté a {self.team} le {self.enter_day} a quité le {self.exit_day}")

project/apps/dash/forms.py
from django.forms import ModelForm, HiddenInput, TimeField, TextInput
from django import forms
from apps.pointage.models import User, Employe, Team, Planing, Day
from django.db.models import Q
from crispy_forms.helper import FormHelper

class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['role'].widget = HiddenInput()

    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email','role' ]
        help_texts = {
            'username': None,
        }
        widgets = {
        'username': forms.TextInput(attrs={'readonly': 'readonly'}),
        'last_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'first_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'email': forms.TextInput(attrs={'readonly': 'readonly'}),
        'role': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

class EditUserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['role'].widget = HiddenInput()

    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email','role' ]
        widgets = {
        'last_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'first_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'role': forms.TextInput(attrs={'readonly': 'readonly'}),
        }
        help_texts = {
            'username': None,
        }
        

class EmployeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EmployeForm, self).__init__(*args, **kwargs)
        self.fields['planing'].widget = HiddenInput()

    class Meta:
        model = Employe
        fields = ['user', 'birthdate', 'birthplace', 'address', 'phone1', 'phone2', 'description', 'gender','planing', 'observation']
        widgets = {
            'user': forms.TextInput(attrs={'readonly': 'readonly'}),
            'birthdate': forms.TextInput(attrs={'readonly': 'readonly'}),
            'birthplace': forms.TextInput(attrs={'readonly': 'readonly'}),
            'address': forms.TextInput(attrs={'readonly': 'readonly'}),
            'phone1': forms.TextInput(attrs={'readonly': 'readonly'}),
            'phone2': forms.TextInput(attrs={'readonly': 'readonly'}),
            'description': forms.Textarea(attrs={'readonly': 'readonly','rows': 3}),
            'gender': forms.TextInput(attrs={'readonly': 'readonly'}),
            'planing': forms.TextInput(attrs={'readonly': 'readonly'}),  
            
            }

class EditEmployeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditEmployeForm, self).__init__(*args, **kwargs)
        self.fields['planing'].widget = HiddenInput()

    class Meta:
        model = Employe
        fields = ['user', 'birthdate', 'birthplace', 'address', 'phone1', 'phone2', 'description', 'picture', 'gender','planing', 'observation']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'picture':forms.FileInput(attrs={'class':'custom-file-input' }) 
        }



class TeamForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):     
        super (TeamForm,self ).__init__(*args,**kwargs) 
        if 'instance' in kwargs :
            team = kwargs.pop('instance')
        else:
            team = None

        if team == None:
            self.fields['manager'].queryset = Employe.objects.filter(user__role=2, managed_team=None)
        else:
            try:
                self.fields['manager'].queryset = Employe.objects.filter(Q(user__role=2),( Q(user=team.manager.user) | Q(managed_team=None) ))
                self.fields['manager'].initial = team.manager
            except:
                self.fields['manager'].queryset = Employe.objects.filter(Q(user__role=2), Q(managed_team=None) )
                print("Manager does not exists")

    class Meta:
        model = Team
        fields = ['id', 'titre', 'description', 'manager' ]

class PlanningForm(forms.ModelForm):

    class Meta:
        model = Planing
        fields =    '__all__'

class DayForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DayForm, self).__init__(*args, **kwargs)
        days = ['Lundi', 'Mardi', 'Mercredi' , 'Jeudi' , 'Vendredi', 'Samedi', 'Dimanche']
        # Hide jds field
        self.fields['jds'].widget = HiddenInput()
        # Get FormHelper to remove all labels
        self.helper = FormHelper()
        self.helper.form_show_labels = False 
        if 'initial' in kwargs:
            t = kwargs.get('initial').get('jds')
            self.day= days[t]
        else:
            print("None")

        if 'instance' in kwargs :
            instance = kwargs.pop('instance')
            self.day=days[instance.jds]
        else:
            team = None
        
        # Adding placeholder to fields
        self.fields['he1'].widget.attrs['placeholder'] = "Heure d'entré"
        self.fields['hs1'].widget.attrs['placeholder'] = "Heure de sortie"
        self.fields['he2'].widget.attrs['placeholder'] = "Heure d'entré"
        self.fields['hs2'].widget.attrs['placeholder'] = "Heure de sortie"
        

    class Meta:
        model = Day
        fields =    '__all__'

   
    

project/templates/dash/assign_team.html
{% extends "base_generic.html" %}
{% block nav %} {% endblock %}
{% block title %} project manger dashbored {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container-fluid">
        <div class="form-modify">

            <div class="title" >
                <div class="ligne">
                    <h1>{{ form.titre.value|capfirst }}</h1>
                    <div class="div">
                        <a class="btn btn-primary" href="{% url 'dash:modify_team' pk=pk %}" role="button" aria-pressed="true">Modifier l'équipe</a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteTeamModal">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </div>
                </div>
                <div class="trait"></div>
            </div>

            <div class="modal fade" id="deleteTeamModal" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="deleteTeamModalLabel">Voulez-vous vraiment supprimer cette équipe?</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
    
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                      <a class="btn btn-primary" href="{% url 'dash:delete_team' pk=pk %}" role="button" aria-pressed="true">Confirmer la suppression</a>
                    </div>
                  </div>
                </div>
              </div>

                <form method='post'>
                    {% csrf_token %}
                    <div class="row align-items-end">
                        <div class="form-group col-md-6 mb-0">
                          {{ form.titre|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.manager|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-12 mb-0">
                          {{ form.description|as_crispy_field }}
                        </div>
                    </div>
                </form>

                <form method='post'>
                    {% csrf_token %}
                    <div class="row align-items-end">
                        <div class="form-group col-md-6 mb-0">
                            <label for="formGroupExampleInput">Ajouter un employé</label>
                            <input type="text" class="form-control" id="employe" placeholder="Entré le nom de l'employé" name="employe">
                        </div>
                        <div class="form-group col-md-6 mb-0 ">
                            <input class="btn btn-success btn-block" type='submit' value="Ajouter l'employé" name="add">
                        </div>
                    </div>
                </form>

        </div>
        <div class="employes">
                    <div class="row">
                        <div class="table-responsive">
                            <table class="table table-striped table-my-collaborator-responsable">
                                <thead>
                                <tr>
                                    <th scope="row">#</th>
                                    <th scope="row">Employé</th>
                                    <th scope="row">Status</th>
                                    <th scope="row">Genre</th>
                                    <th scope="row">Téléphone</th>
                                </tr>
                                </thead>
                                <tbody>
                                        {% for employe  in employes %}
                                            <tr>
                                                <td>{{ employe.user.pk  }}</td>
                                                <td class="employe-name">
                                                    <img src="{{ employe.picture.url }}" class="profile-pic rounded-circle" alt="">
                                                    <p>{{ employe.user.last_name|upper  }} {{ employe.user.first_name|capfirst }}</p>
                                                </td>
                                                <td>
                                                    {% if employe.iwssad %}
                                                        Present
                                                    {% else %}
                                                        Sortie
                                                    {% endif%}
                                                </td>
                                                <td>
                                                    {% if employe.gender != F %}
                                                        Homme
                                                    {% else %}
                                                        Femme
                                                    {% endif%}
                                                </td>
                                                <td>
                                                    {% if employe.phone1 != None %}
                                                        {{ employe.phone1 }}
                                                    {% else %}
                                                        /
                                                    {% endif%}
                                                    
                                                    
                                                    <div class="btn-group ">
                                                        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                                            <i class="fas fa-ellipsis-v"></i>   
                                                        </a>
                                                        <div class="dropdown-menu dropdown-menu-right">
                                                          <a class="dropdown-item" href="{% url 'dash:view_profile' pk=employe.user.pk %}">Voir le profile</a>
                                                          <a class="dropdown-item" href="{% url 'dash:ma_fiche_pointage' pk=employe.user.pk %}">Voir la fiche de pointage</a>
                                                          <div class="dropdown-divider"></div>
                                                          <a class="dropdown-item" value="delete" data-toggle="modal" data-target="#deleteTEmploye{{employe.user.pk}}">Supprimer de l'équipe</a>
                                                        </div>
                                                      </div>
                                                    
                                                  
                                                </td> 
                                            </tr>

                                            <!-- Modal -->
                                            <div class="modal fade" id="deleteTEmploye{{employe.user.pk}}" tabindex="-1" role="dialog" aria-hidden="true">
                                                <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteTEmployeLabel">Voulez-vous vraiment supprimer cette employé?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    </div>
                                                    <div class="modal-footer">      
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <a  class="btn btn-primary" href="{% url 'dash:delete_employe_team' pk=employe.user.pk %}" role="button" aria-pressed="true">Confirmer la suppression</a>
                                                    </div>
                                                </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                </tbody>
                            </table>
                        </div>
                </div>
        </div>
    </div>

 
    
{% endblock %}

{% block scripts %}
<script>
    $( function() {
      $( "#employe" ).autocomplete({
        source: "{% url 'dash:assign_team' pk=form.initial %}"
      });
    } );
    </script>
{% endblock %}

project/templates/dash/create_team.html
{% extends "base_generic.html" %}
{% block nav %} {% endblock %}
{% block title %} project manger dashbored {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container">
        <div class="form-create">
            <h1>Crée une nouvelle équipe</h1>
            <div class="trait"></div>

                <form method='post'>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary btn-block" type='submit' value="Crée l'équipe" name="create">
                </form>
            </div>
        </div>
    </div>

    {{ test }}
    
{% endblock %}

{% block scripts %}
{% endblock %}

project/templates/dash/mes_equipes.html
{% extends "base_generic.html" %} {% block nav %} {% endblock %} {% block title %}Manager dashbored {% endblock %}
{% block content %}


 <div class="container-fluid">
        <div class="team">
            <div class="title">
                <div class="ligne">
                    <h1>Mes équipes</h1>

                </div>
                <div class="trait"></div>
            </div>
    
            <div class="row">
                {% if teams %}
                    {% if teams_nbr > 1 %}
                    {% for team in teams %}
                        <div class="col-xl-3 col-md-4 col-sm6">
                            <div class="card card-team">     
                                <h3 class="title-team">{{ team.titre }}</h3>
                                <div class="description-team">
                                    {% if team.manager.user.first_name %}
                                        <h5>{{ team.manager.user.first_name }} {{ team.manager.user.last_name }}</h5>
                                    {% else %}
                                        <h5>Aucun manager</h5>
                                    {% endif %}
                                    <p>{{ team.description|truncatechars:22  }}</p>
                                </div>
                                <div class="heure-e">
                                    <p>{{ team.nb_emp }}</p>
                                    <p>{{ team.nb_emp_in }}</p>
                                </div>
                                <a class="btn more" href="{% url 'dash:equipe_view' pk=team.id %}">
                                    <i class="fas fa-chevron-right more-icon"></i>
                                </a>
                            
                            </div>
                            
                        </div>   
                    {% endfor %}
                                           
                    {% endif%}
                
               
                {% endif %}
               
                    
                
            
            </div>
 
            </div>
        </div>
    </div>  





    

{% block scripts %}



{% endblock scripts %} 
{% endblock %}