project/apps/dash/urls.py
from django.urls import path, include
from . import views

app_name = 'dash'
urlpatterns = [
    path('dashboard_emp', views.dash_emp, name='employe_dashbored'),
    path('dashboard_man', views.dash_man, name='manager_dashbored'),
    path('dashboard_responsible', views.dash_responsible, name='responsible_dashbored'),
    path('profile', views.profile , name='profile'),
    path('profile/<str:pk>', views.view_profile , name='view_profile'),
    path('edit_profile/<str:pk>', views.edit_profile , name='edit_profile'),
    path('ma_fiche_pointage/<str:pk>', views.ma_fiche_pointage , name='ma_fiche_pointage'),
    path('fiche_pointage/', views.fiche_pointage , name='fiche_pointage'),
    path('mes_collaborateurs', views.mes_collaborateurs , name='mes_collaborateurs'),
    path('my_teams', views.my_teams , name='my_teams'),
    path('schedules', views.schedules , name='schedules'),
    path('schedule/<str:pk>', views.schedule , name='schedule'),
    path('my_schedule/<str:pk>', views.my_schedule , name='my_schedule'),
    path('modify_schedule/<str:pk>', views.modify_schedule , name='modify_schedule'),
    path('assign_schedule/<str:pk>', views.assign_schedule , name='assign_schedule'),
    path('create_schedule', views.create_schedule , name='create_schedule'),
    path('delete_schedule/<str:pk>', views.delete_schedule , name='delete_schedule'),
    path('delete_employe_schedule/<str:pk>', views.delete_employe_schedule , name='delete_employe_schedule'),
    path('create_team', views.create_team , name='create_team'),
    path('assign_team/<str:pk>', views.assign_team , name='assign_team'),
    path('modify_team/<str:pk>', views.modify_team , name='modify_team'),
    path('delete_team/<str:pk>', views.delete_team , name='delete_team'),
    path('delete_employe_team/<str:pk>', views.delete_employe_team , name='delete_employe_team'),
    path('mes_employes', views.mes_employes , name='mes_employes'),
    path('fiche_pointage_all/', views.fiche_pointage_all , name='fiche_pointage_all'),
    path('mes_equipes/', views.mes_equipes , name='mes_equipes'),
    path('equipe_view/<str:pk>', views.equipe_view , name='equipe_view'), 
    path('affectations_view/', views.affectations_view , name='affectations_view'), 


    #path('mon-equipe/', views.mon_equipe , name='mon_equipe'),
    path('export_shift/', views.export_shift , name='export_shift'),
    path('import_shift/', views.import_shift , name='import_shift'),

    
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pointage/', include('apps.pointage.urls', namespace='pointage')),
    path('dash/', include('apps.dash.urls', namespace='dash')),
    path('', include('apps.authentification.urls', namespace='authentification')),
    path('', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/dash/models.py
from django.db import models


# Create your models here.

project/apps/dash/forms.py
from django.forms import ModelForm, HiddenInput, TimeField, TextInput
from django import forms
from apps.pointage.models import User, Employe, Team, Planing, Day
from django.db.models import Q
from crispy_forms.helper import FormHelper

class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['role'].widget = HiddenInput()

    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email','role' ]
        help_texts = {
            'username': None,
        }
        widgets = {
        'username': forms.TextInput(attrs={'readonly': 'readonly'}),
        'last_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'first_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'email': forms.TextInput(attrs={'readonly': 'readonly'}),
        'role': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

class EditUserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['role'].widget = HiddenInput()

    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email','role' ]
        widgets = {
        'last_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'first_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        'role': forms.TextInput(attrs={'readonly': 'readonly'}),
        }
        help_texts = {
            'username': None,
        }
        

class EmployeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EmployeForm, self).__init__(*args, **kwargs)
        self.fields['planing'].widget = HiddenInput()

    class Meta:
        model = Employe
        fields = ['user', 'birthdate', 'birthplace', 'address', 'phone1', 'phone2', 'description', 'gender','planing', 'observation']
        widgets = {
            'user': forms.TextInput(attrs={'readonly': 'readonly'}),
            'birthdate': forms.TextInput(attrs={'readonly': 'readonly'}),
            'birthplace': forms.TextInput(attrs={'readonly': 'readonly'}),
            'address': forms.TextInput(attrs={'readonly': 'readonly'}),
            'phone1': forms.TextInput(attrs={'readonly': 'readonly'}),
            'phone2': forms.TextInput(attrs={'readonly': 'readonly'}),
            'description': forms.Textarea(attrs={'readonly': 'readonly','rows': 3}),
            'gender': forms.TextInput(attrs={'readonly': 'readonly'}),
            'planing': forms.TextInput(attrs={'readonly': 'readonly'}),  
            
            }

class EditEmployeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditEmployeForm, self).__init__(*args, **kwargs)
        self.fields['planing'].widget = HiddenInput()

    class Meta:
        model = Employe
        fields = ['user', 'birthdate', 'birthplace', 'address', 'phone1', 'phone2', 'description', 'picture', 'gender','planing', 'observation']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'picture':forms.FileInput(attrs={'class':'custom-file-input' }) 
        }



class TeamForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):     
        super (TeamForm,self ).__init__(*args,**kwargs) 
        if 'instance' in kwargs :
            team = kwargs.pop('instance')
        else:
            team = None

        if team == None:
            self.fields['manager'].queryset = Employe.objects.filter(user__role=2, managed_team=None)
        else:
            try:
                self.fields['manager'].queryset = Employe.objects.filter(Q(user__role=2),( Q(user=team.manager.user) | Q(managed_team=None) ))
                self.fields['manager'].initial = team.manager
            except:
                self.fields['manager'].queryset = Employe.objects.filter(Q(user__role=2), Q(managed_team=None) )
                print("Manager does not exists")

    class Meta:
        model = Team
        fields = ['id', 'titre', 'description', 'manager' ]

class PlanningForm(forms.ModelForm):

    class Meta:
        model = Planing
        fields =    '__all__'

class DayForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DayForm, self).__init__(*args, **kwargs)
        days = ['Lundi', 'Mardi', 'Mercredi' , 'Jeudi' , 'Vendredi', 'Samedi', 'Dimanche']
        # Hide jds field
        self.fields['jds'].widget = HiddenInput()
        # Get FormHelper to remove all labels
        self.helper = FormHelper()
        self.helper.form_show_labels = False 
        if 'initial' in kwargs:
            t = kwargs.get('initial').get('jds')
            self.day= days[t]
        else:
            print("None")

        if 'instance' in kwargs :
            instance = kwargs.pop('instance')
            self.day=days[instance.jds]
        else:
            team = None
        
        # Adding placeholder to fields
        self.fields['he1'].widget.attrs['placeholder'] = "Heure d'entré"
        self.fields['hs1'].widget.attrs['placeholder'] = "Heure de sortie"
        self.fields['he2'].widget.attrs['placeholder'] = "Heure d'entré"
        self.fields['hs2'].widget.attrs['placeholder'] = "Heure de sortie"
        

    class Meta:
        model = Day
        fields =    '__all__'

   
    

project/apps/dash/views.py
from django.shortcuts import render, HttpResponseRedirect
from .decorators import employe_required, manger_required, project_manger_required
from django.contrib.auth.decorators import login_required
from apps.pointage.models import Employe, User, Planing, Shift
from django.core.exceptions import ObjectDoesNotExist
from .forms import UserForm
from django.urls import reverse
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.utils import timezone
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import  Q


# Create your views here.

# to convert naif datetime to number of hours and min
def convert_time(time):
    days, seconds = time.days, time.seconds
    hours = days * 24 + seconds // 3600
    minutes = (seconds % 3600) // 60
    return "%sh%smin" % (hours, minutes)

def is_valid(param):
    if param != None and param != '':
        return True

@employe_required
def dash_emp(request):
    # Get employe with id
    emp = Employe.objects.filter(user=request.user).get()
    # Get date time when the employe begin work
    time=emp.get_start_time()
    # start time - time now
    print("-----", time)
    print("-----", timezone.now().time())
    date = datetime.date(1, 1, 1)
    datetime1 = datetime.datetime.combine(date, timezone.now().time())
    datetime2 = datetime.datetime.combine(date, time)
    work_time =  datetime1-datetime2
    # return template with context after convert work_time to hours and min
    return render(request, 'dash/dash_emp.html',{'time':time, 'work_time':convert_time(work_time)})


@manger_required
def dash_man(request):
    # Get current user manager
    emp_man = Employe.objects.filter(user=request.user).get()
    # Get number of employe --> total/inside/outside
    print(emp_man.team)
    if emp_man.team != None:
        man_employe_stats = Employe.manager.get_my_employe_stats(team=emp_man.team, user_emp=request.user).get()
        team_name = emp_man.team.nom
    # Get all employe of current manager
        man_employe = Employe.manager.get_my_employe(team=emp_man.team, user_emp=request.user)
    else:
        man_employe_stats = None
        team_name = None
        man_employe = None

    return render(request, 'dash/dash_man.html', {'man_employe_stats':man_employe_stats, 'team_name':team_name, 'man_employe':man_employe})


@project_manger_required
def dash_pro_man(request):
    return render(request, 'dash/dash_pro_man.html', {'test':4})

@login_required
def profile(request):
    # Get the user
    user = request.user
    # Prepopulate UserForm with data
    user_form = UserForm(instance=user)
    # Create grouped form User/Employe 
    EmployeFormset = inlineformset_factory(User, Employe, fields=('birthdate', 'birthplace', 'address', 'phone1', 'phone2', 'observation', 'picture', 'gender'), can_delete=False)
    # Prepopulate EmployeForm with user pk
    formset = EmployeFormset(instance=user)
 
    if request.user.id == user.id:
        if request.method == "POST":
            # get data from POST method
            user_form = UserForm(request.POST, request.FILES, instance=user)
            formset = EmployeFormset(request.POST, request.FILES, instance=user)
            formset.picture = request.FILES.get('picture')
            # If user_form is valide save data
            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = EmployeFormset(request.POST, request.FILES, instance=created_user)
                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect(reverse('dash:profile'))
 
        return render(request, "dash/profile.html", {
            "user_form": user_form,
            "formset": formset,
        })
  

@login_required  
def view_profile(request, pk):
    # Get the user
    user = User.objects.get(id=pk)
    # Prepopulate UserForm with data
    user_form = UserForm(instance=user)
    # Create grouped form User/Employe 
    EmployeFormset = inlineformset_factory(User, Employe, fields=('birthdate', 'birthplace', 'address', 'phone1', 'phone2', 'observation', 'picture', 'gender'), can_delete=False)
    # Prepopulate EmployeForm with user pk
    formset = EmployeFormset(instance=user)
 
    if request.user.id == user.id or request.user.role == 3:
        if request.method == "POST":
            # get data from POST method
            user_form = UserForm(request.POST, request.FILES, instance=user)
            formset = EmployeFormset(request.POST, request.FILES, instance=user)
            # If user_form is valide save data
            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = EmployeFormset(request.POST, request.FILES, instance=created_user)
                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect(reverse('dash:view_profile', kwargs={'pk': pk}))
 
        if request.GET.get('edit_profile') == pk:
            return render(request, "dash/profile.html", {
            "user_form": user_form,
            "formset": formset,
            "check": False,
            })
        else:
            return render(request, "dash/profile.html", {
            "user_form": user_form,
            "formset": formset,
            "check": pk,
            })

    else:
        return HttpResponseRedirect(reverse('authentification:logout'))

@login_required
def ma_fiche_pointage(request):  
    emp = Employe.objects.filter(user=request.user).get()
    # Get shifts of the current employe
    shift_list = Shift.objects.filter(employe=emp).order_by('-day')
    # Check if request method is GET
    if request.GET: 
        # Get str data from fields start and end
        start = request.GET.get('start')
        end = request.GET.get('end')
        # Check if not None or ''
        if is_valid(start) and is_valid(end):
            # Convert str to datetime
            start = datetime.datetime.strptime(start, "%d/%m/%Y")
            end = datetime.datetime.strptime(end, "%d/%m/%Y")
            # Filter shift_list with date params
            shift_list=shift_list.filter(Q(day__gte=start), Q(day__lte=end))
    # Pagginite my list by 7
    paginator = Paginator(shift_list, 7)
    # Get id of page from link if empty --> default=1
    page = request.GET.get('page', 1)
    # Get list shift with page number with exceptions if not integer get first page/ if page contains no results get the last page
    try:
        shifts = paginator.page(page)
    except PageNotAnInteger:
        shifts = paginator.page(1)
    except EmptyPage:
        shifts = paginator.page(paginator.num_pages)
    
    return render(request, 'dash/ma_fiche_pointage.html', {'shifts': shifts})


@manger_required
def mes_collaborateurs(request):
    return render(request, 'dash/mes_collaborateurs.html')

project/templates/dash/responsable/assign_schedule.html
{% extends "base_generic.html" %}
{% block nav %} {% endblock %}
{% block title %} project manger dashbored {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container-fluid">
        <div class="form-modify">
            <div class="title" >
                <div class="ligne">
                    <h1>Assigner le planning</h1>
                    
                </div>
                <div class="trait"></div>
            </div>

                <form method='post'>
                    {% csrf_token %}
                    <div class="row align-items-end">
                        <div class="form-group col-md-6 mb-0">
                            <label for="formGroupExampleInput">Ajouter un employé</label>
                            <input type="text" class="form-control" id="employe" placeholder="Entré le nom de l'employé" name="employe">
                        </div>
                        <div class="form-group col-md-6 mb-0 ">
                            <input class="btn btn-success btn-block" type='submit' value="Ajouter" name="add">
                        </div>
                    </div>
                </form>

        </div>
        <div class="employes">
                    <div class="row">
                        <div class="table-responsive">
                            <table class="table table-striped table-my-collaborator-responsable">
                                <thead>
                                <tr>
                                    <th scope="row">ID</th>
                                    <th scope="row">Employé</th>
                                    <th scope="row">Status</th>
                                    <th scope="row">Genre</th>
                                    <th scope="row">Téléphone</th>
                                </tr>
                                </thead>
                                <tbody>
                                        {% for employe  in employes %}
                                            <tr>
                                                <td>{{ employe.user.pk  }}</td>
                                                <td class="employe-name">
                                                    <img src="{{ employe.picture.url }}" class="profile-pic rounded-circle" alt="">
                                                    <p>{{ employe.user.last_name|upper  }} {{ employe.user.first_name|capfirst }}</p>
                                                </td>
                                                <td>
                                                    {% if employe.iwssad %}
                                                        Present
                                                    {% else %}
                                                        Sortie
                                                    {% endif%}
                                                </td>
                                                <td>
                                                    {% if employe.gender != F %}
                                                        Homme
                                                    {% else %}
                                                        Femme
                                                    {% endif%}
                                                </td>
                                                <td>
                                                    {% if employe.phone1 != None %}
                                                        {{ employe.phone1 }}
                                                    {% else %}
                                                        /
                                                    {% endif%}
                                                    
                                                    
                                                    <div class="btn-group ">
                                                        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                                            <i class="fas fa-ellipsis-v"></i>   
                                                        </a>
                                                        <div class="dropdown-menu dropdown-menu-right">
                                                          <a class="dropdown-item" href="{% url 'dash:view_profile' pk=employe.user.pk %}">Voir le profile</a>
                                                          <a class="dropdown-item" href="{% url 'dash:ma_fiche_pointage' pk=employe.user.pk %}">Voir la fiche de pointage</a>
                                                          <div class="dropdown-divider"></div>
                                                          <a class="dropdown-item" value="delete" data-toggle="modal" data-target="#deletePEmploye{{employe.user.pk}}">Supprimer du planning</a>
                                                        </div>
                                                      </div>

                                                      
                                                    
                                                  
                                                </td> 
                                            </tr>

                                            <!-- Modal -->
                                            <div class="modal fade" id="deletePEmploye{{employe.user.pk}}" tabindex="-1" role="dialog" aria-hidden="true">
                                                <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                    <h5 class="modal-title" id="deletePEmployeLabel">Voulez-vous vraiment supprimer cette employé?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    </div>
                                                    <div class="modal-footer">      
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <a  class="btn btn-primary" href="{% url 'dash:delete_employe_schedule' pk=employe.user.pk %}" role="button" aria-pressed="true">Confirmer la suppression</a>
                                                    </div>
                                                </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                </tbody>
                            </table>
                        </div>
                </div>
        </div>
    </div>

 
    
{% endblock %}

{% block scripts %}
<script>
    $( function() {
      $( "#employe" ).autocomplete({
        source: "{% url 'dash:assign_schedule' pk=pk %}"
      });
    } );
    </script>
{% endblock %}

project/templates/dash/responsable/modify_team.html
{% extends "base_generic.html" %}
{% block nav %} {% endblock %}
{% block title %} project manger dashbored {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container">
        <div class="form-create">
            <h1>Modifier l'équipe</h1>
            <div class="trait"></div>

                <form method='post'>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary btn-block" type='submit' value="Enregistrer les modifications" name="create">
                </form>
            </div>
        </div>
    </div>

    {{ test }}
    
{% endblock %}

{% block scripts %}
{% endblock %}

project/templates/dash/responsable/schedule.html
{% extends "base_generic.html" %}
{% block nav %} {% endblock %}
{% block title %} project manger dashbored {% endblock %}
{% load crispy_forms_tags %}

{% block scripts %}
<script> 
  
  
  google.charts.load("current", {packages:["timeline"], 'language': 'fr'});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {

    var container = document.getElementById('schedule');
    var chart = new google.visualization.Timeline(container);
    var dataTable = new google.visualization.DataTable();

    dataTable.addColumn({
      type: 'string',
      id: 'President'
    });
    dataTable.addColumn({
      type: 'string',
      id: 'Category'
    });
    dataTable.addColumn({
      type: 'date',
      id: 'Start'
    });
    dataTable.addColumn({
      type: 'date',
      id: 'End'
    });
    
    dataTable.addRows([
        {% for key,value in row.items %}
            [ "{{value.jours}}", "{{value.title}}",  new Date("{{value.he1}}"),  new Date("{{value.hs1}}") ],
            [ "{{value.jours}}", "{{value.title}}",   new Date("{{value.he2}}"),  new Date("{{value.hs2}}") ],
        {% endfor %}
    ]);

    var rowHeight = 24;
    var chartHeight = dataTable.getNumberOfRows() * rowHeight + 50;

    var options = {
        timeline: {
            groupByRowLabel: true,
        },
        backgroundColor: '#ffffff',
        height : chartHeight,
        hAxis: {
            format: 'HH:mm',                      
        },
    };
    // add event to make haxis on top
    google.visualization.events.addListener(chart, 'ready', afterDraw);

    chart.draw(dataTable, options);
	(function(){											//anonymous self calling function to prevent variable name conficts
		var el=container.getElementsByTagName("rect");		//get all the descendant rect element inside the container		
		var width=100000000;								//set a large initial value to width
		var elToRem=[];										//element would be added to this array for removal
		for(var i=el.length;i--;){							//looping over all the rect element of container
			var cwidth=parseInt(el[i].getAttribute("width"));//getting the width of ith element
			if(cwidth<width){								//if current element width is less than previous width then this is min. width and ith element should be removed
				elToRem=[el[i]];
				width=cwidth;								//setting the width with min width
			}
			else if(cwidth==width){							//if current element width is equal to previous width then more that one element would be removed
				elToRem.push(el[i]);		
			}
		}
		for(i=elToRem.length;i--;)
			elToRem[i].setAttribute("fill","none");	//invisiblize all the rect element which has minimum width
    })();
    
    
}

function afterDraw() {
      	var g = document.getElementsByTagName("svg")[0].getElementsByTagName("g")[1];
        document.getElementsByTagName("svg")[0].parentNode.style.top = '40px';
        document.getElementsByTagName("svg")[0].style.overflow = 'visible';
        var height = Number(g.getElementsByTagName("text")[0].getAttribute('y')) + 15;
        g.setAttribute('transform','translate(0,-'+height+')');
        g = null;
}

$(window).resize(function() {
    if(this.resizeTO) clearTimeout(this.resizeTO);
    this.resizeTO = setTimeout(function() {
        $(this).trigger('resizeEnd');
    }, 500);
});

//redraw graph when window resize is completed  
$(window).on('resizeEnd', function() {
    drawChart();
    console.log('click');
});


</script>
{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="title" >
            <div class="ligne">
                <h1>Le planning</h1>
                <div class="div">
                    {% if request.user.role == 3 %}
                        <a class="btn btn-primary" href="{% url 'dash:assign_schedule' pk=schedule.id %}" role="button" aria-pressed="true">Affecter le planning</a>
                        <a class="btn btn-primary" href="{% url 'dash:modify_schedule' pk=schedule.id %}" role="button" aria-pressed="true"><i class="far fa-edit"></i></a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteScheduleModal">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    {% endif %}
                </div>
            </div>
            <div class="trait"></div>
        </div>

        <div class="row">

            <div class="col-lg-4 col-sm-6">
                <div class="card-schedule">
                    <div class="info">
                        <h3> {{ schedule.titre }} </h3>
                        <p> {{ schedule.description}} </p>
                    </div>
                    <div class="icon ">
                        <i class="fas fa-calendar-week"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-sm-6">
                <div class="card-schedule">
                    <div>
                        <h3> Employé assigner </h3>
                        <p> {{ schedule.nb_emp }} </p>
                    </div>
                    <div class="icon ">
                        <i class="fas fa-user"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-sm-6">
                <div class="card-schedule">
                    <div>
                        <h3> Nombre d'heures</h3>
                        <p> {{ schedule.total }} </p>
                    </div>
                    <div class="icon ">
                        <i class="far fa-clock"></i>
                    </div>
                </div>
            </div>
        </div>
            
        <div class="row">
            <div class="col-xl-12 chart">
                <div id="schedule"></div>
            </div>
        </div>

        <div class="modal fade" id="deleteScheduleModal" tabindex="-1" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteScheduleModalLabel">Voulez-vous vraiment supprimer ce planning?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                  <a class="btn btn-primary" href="{% url 'dash:delete_schedule' pk=schedule.id %}" role="button" aria-pressed="true">Confirmer la suppression</a>
                </div>
              </div>
            </div>
          </div>
            
       
    </div>
    
{% endblock %}